//
//  Plate.swift
//  Blagaprint
//
//  Created by Ivan Magda on 01.12.15.
//  Copyright (c) 2015 Blagaprint. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class Plate : NSObject {

    //// Drawing Methods

    public class func drawPlateCanvas(frame frame: CGRect = CGRectMake(40, 20, 320, 320), image: UIImage = UIImage(named: "image.png")!, isPlateImageVisible: Bool = true) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()

        //// Color Declarations
        let shadowColor = UIColor(red: 0.674, green: 0.675, blue: 0.663, alpha: 1.000)
        let color = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 0.000)
        let plateInnerShadowColor = UIColor(red: 0.667, green: 0.675, blue: 0.663, alpha: 1.000)
        let gold = UIColor(red: 0.831, green: 0.686, blue: 0.216, alpha: 1.000)

        //// Shadow Declarations
        let outerShadow = NSShadow()
        outerShadow.shadowColor = UIColor.grayColor().colorWithAlphaComponent(0.5)
        outerShadow.shadowOffset = CGSizeMake(16.1, 2.1)
        outerShadow.shadowBlurRadius = 15
        let plateInnerShadow = NSShadow()
        plateInnerShadow.shadowColor = plateInnerShadowColor.colorWithAlphaComponent(0.1 * CGColorGetAlpha(plateInnerShadowColor.CGColor))
        plateInnerShadow.shadowOffset = CGSizeMake(13.1, 5.1)
        plateInnerShadow.shadowBlurRadius = 10

        //// Variable Declarations
        let expression: CGFloat = isPlateImageVisible == true ? 0 : 0.1

        //// Oval Drawing
        let ovalPath = UIBezierPath(ovalInRect: CGRectMake(frame.minX + 10.25, frame.minY + 14.75, 290, 290))
        CGContextSaveGState(context)
        CGContextSetShadowWithColor(context, outerShadow.shadowOffset, outerShadow.shadowBlurRadius, (outerShadow.shadowColor as! UIColor).CGColor)
        UIColor.whiteColor().setFill()
        ovalPath.fill()

        ////// Oval Inner Shadow
        CGContextSaveGState(context)
        CGContextClipToRect(context, ovalPath.bounds)
        CGContextSetShadow(context, CGSizeMake(0, 0), 0)
        CGContextSetAlpha(context, CGColorGetAlpha((plateInnerShadow.shadowColor as! UIColor).CGColor))
        CGContextBeginTransparencyLayer(context, nil)
        let ovalOpaqueShadow = (plateInnerShadow.shadowColor as! UIColor).colorWithAlphaComponent(1)
        CGContextSetShadowWithColor(context, plateInnerShadow.shadowOffset, plateInnerShadow.shadowBlurRadius, ovalOpaqueShadow.CGColor)
        CGContextSetBlendMode(context, .SourceOut)
        CGContextBeginTransparencyLayer(context, nil)

        ovalOpaqueShadow.setFill()
        ovalPath.fill()

        CGContextEndTransparencyLayer(context)
        CGContextEndTransparencyLayer(context)
        CGContextRestoreGState(context)

        CGContextRestoreGState(context)

        gold.setStroke()
        ovalPath.lineWidth = 0.5
        ovalPath.stroke()


        if (isPlateImageVisible) {
            //// Oval 2 Drawing
            let oval2Rect = CGRectMake(frame.minX + 40, frame.minY + 45, 230, 230)
            let oval2Path = UIBezierPath(ovalInRect: oval2Rect)
            CGContextSaveGState(context)
            oval2Path.addClip()
            image.drawInRect(CGRectMake(floor(oval2Rect.minX + 0.5), floor(oval2Rect.minY + 0.5), image.size.width, image.size.height))
            CGContextRestoreGState(context)
        }


        //// Depth Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, frame.minX + 154.55, frame.minY + 160.45)

        let depthPath = UIBezierPath(ovalInRect: CGRectMake(-124.55, -125.45, 250, 250))
        color.setFill()
        depthPath.fill()

        ////// Depth Inner Shadow
        CGContextSaveGState(context)
        CGContextClipToRect(context, depthPath.bounds)
        CGContextSetShadow(context, CGSizeMake(0, 0), 0)
        CGContextSetAlpha(context, CGColorGetAlpha((plateInnerShadow.shadowColor as! UIColor).CGColor))
        CGContextBeginTransparencyLayer(context, nil)
        let depthOpaqueShadow = (plateInnerShadow.shadowColor as! UIColor).colorWithAlphaComponent(1)
        CGContextSetShadowWithColor(context, plateInnerShadow.shadowOffset, plateInnerShadow.shadowBlurRadius, depthOpaqueShadow.CGColor)
        CGContextSetBlendMode(context, .SourceOut)
        CGContextBeginTransparencyLayer(context, nil)

        depthOpaqueShadow.setFill()
        depthPath.fill()

        CGContextEndTransparencyLayer(context)
        CGContextEndTransparencyLayer(context)
        CGContextRestoreGState(context)

        gold.setStroke()
        depthPath.lineWidth = 0.3
        depthPath.stroke()

        CGContextRestoreGState(context)


        //// Depth 2 Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, frame.minX + 154.59, frame.minY + 160.41)

        let depth2Path = UIBezierPath(ovalInRect: CGRectMake(-114.59, -115.41, 230, 230))
        color.setFill()
        depth2Path.fill()
        shadowColor.setStroke()
        depth2Path.lineWidth = expression
        depth2Path.stroke()

        CGContextRestoreGState(context)
    }

    //// Generated Images

    public class func imageOfPlateCanvas(frame frame: CGRect = CGRectMake(40, 20, 320, 320), image: UIImage = UIImage(named: "image.png")!, isPlateImageVisible: Bool = true) -> UIImage {
        UIGraphicsBeginImageContextWithOptions(frame.size, false, 0)
            Plate.drawPlateCanvas(frame: CGRectMake(0, 0, frame.size.width, frame.size.height), image: image, isPlateImageVisible: isPlateImageVisible)

        let imageOfPlateCanvas = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return imageOfPlateCanvas
    }

}
