//
//  SH11_PhotoFrame.swift
//  Blagaprint
//
//  Created by Ivan Magda on 25.11.15.
//  Copyright (c) 2015 Blagaprint. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class SH11_PhotoFrame : NSObject {

    //// Drawing Methods

    public class func drawSH11(frame frame: CGRect = CGRectMake(0, 0, 540, 575), pickedImage: UIImage = UIImage(named: "pickedImage.png")!) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()


        //// Image Declarations
        let sh11_placeholderImage = UIImage(named: "sh11_placeholderImage.jpg")!

        //// PlaceholderRectangle Drawing
        let placeholderRectangleRect = CGRectMake(frame.minX, frame.minY, 540, 575)
        let placeholderRectanglePath = UIBezierPath(rect: placeholderRectangleRect)
        CGContextSaveGState(context)
        placeholderRectanglePath.addClip()
        sh11_placeholderImage.drawInRect(CGRectMake(floor(placeholderRectangleRect.minX + 0.5), floor(placeholderRectangleRect.minY + 0.5), sh11_placeholderImage.size.width, sh11_placeholderImage.size.height))
        CGContextRestoreGState(context)


        //// PickedImageRectangle Drawing
        let pickedImageRectangleRect = CGRectMake(frame.minX + 29, frame.minY + 20, 492, 503)
        let pickedImageRectanglePath = UIBezierPath()
        pickedImageRectanglePath.moveToPoint(CGPointMake(frame.minX + 33, frame.minY + 265))
        pickedImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 29, frame.minY + 514))
        pickedImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 115.43, frame.minY + 515.58))
        pickedImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 115.92, frame.minY + 492))
        pickedImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 145.89, frame.minY + 492))
        pickedImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 145.89, frame.minY + 516))
        pickedImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 378.64, frame.minY + 520.35))
        pickedImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 378.68, frame.minY + 495))
        pickedImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 410.66, frame.minY + 495))
        pickedImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 410.66, frame.minY + 520))
        pickedImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 520.56, frame.minY + 523))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 520.56, frame.minY + 465), controlPoint1: CGPointMake(frame.minX + 520.56, frame.minY + 523), controlPoint2: CGPointMake(frame.minX + 521.56, frame.minY + 499))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 493.58, frame.minY + 422), controlPoint1: CGPointMake(frame.minX + 520.16, frame.minY + 451.52), controlPoint2: CGPointMake(frame.minX + 499.4, frame.minY + 436.99))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 454.62, frame.minY + 358), controlPoint1: CGPointMake(frame.minX + 484.8, frame.minY + 399.4), controlPoint2: CGPointMake(frame.minX + 461.4, frame.minY + 384.02))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 459.61, frame.minY + 318), controlPoint1: CGPointMake(frame.minX + 450.53, frame.minY + 342.32), controlPoint2: CGPointMake(frame.minX + 463.25, frame.minY + 334.48))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 459.61, frame.minY + 231), controlPoint1: CGPointMake(frame.minX + 453.25, frame.minY + 289.24), controlPoint2: CGPointMake(frame.minX + 466.8, frame.minY + 259.56))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 446.65, frame.minY + 154.56), controlPoint1: CGPointMake(frame.minX + 452.37, frame.minY + 202.25), controlPoint2: CGPointMake(frame.minX + 455.58, frame.minY + 180.39))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 435.63, frame.minY + 130), controlPoint1: CGPointMake(frame.minX + 443.73, frame.minY + 146.11), controlPoint2: CGPointMake(frame.minX + 438.72, frame.minY + 137.91))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 377.69, frame.minY + 63), controlPoint1: CGPointMake(frame.minX + 424.74, frame.minY + 102.13), controlPoint2: CGPointMake(frame.minX + 398.03, frame.minY + 80.16))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 328.73, frame.minY + 27), controlPoint1: CGPointMake(frame.minX + 351.18, frame.minY + 40.64), controlPoint2: CGPointMake(frame.minX + 331.32, frame.minY + 27.17))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 228.82, frame.minY + 25), controlPoint1: CGPointMake(frame.minX + 313.74, frame.minY + 26), controlPoint2: CGPointMake(frame.minX + 228.82, frame.minY + 25))
        pickedImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 35.99, frame.minY + 20))
        pickedImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 33, frame.minY + 265))
        pickedImageRectanglePath.closePath()
        CGContextSaveGState(context)
        pickedImageRectanglePath.addClip()
        pickedImage.drawInRect(CGRectMake(floor(pickedImageRectangleRect.minX + 0.5), floor(pickedImageRectangleRect.minY + 0.5), pickedImage.size.width, pickedImage.size.height))
        CGContextRestoreGState(context)
    }

    //// Generated Images

    public class func imageOfSH11(frame frame: CGRect = CGRectMake(0, 0, 540, 575), pickedImage: UIImage = UIImage(named: "pickedImage.png")!) -> UIImage {
        UIGraphicsBeginImageContextWithOptions(frame.size, false, 0)
            SH11_PhotoFrame.drawSH11(frame: CGRectMake(0, 0, frame.size.width, frame.size.height), pickedImage: pickedImage)

        let imageOfSH11 = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return imageOfSH11
    }

}
