//
//  SH15_PhotoFrame.swift
//  Blagaprint
//
//  Created by Ivan Magda on 25.11.15.
//  Copyright (c) 2015 Blagaprint. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class SH15_PhotoFrame : NSObject {

    //// Drawing Methods

    public class func drawSH15(frame frame: CGRect = CGRectMake(0, 0, 817, 461), pickedImage: UIImage = UIImage(named: "pickedImage.png")!) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()


        //// Shadow Declarations
        let outerShadow = NSShadow()
        outerShadow.shadowColor = UIColor.blackColor()
        outerShadow.shadowOffset = CGSizeMake(0.1, -0.1)
        outerShadow.shadowBlurRadius = 10

        //// Image Declarations
        let sh15_placeholderImage = UIImage(named: "sh15_placeholderImage.jpg")!

        //// PlaceholderRectangle Drawing
        let placeholderRectangleRect = CGRectMake(frame.minX, frame.minY, 817, 461)
        let placeholderRectanglePath = UIBezierPath(rect: placeholderRectangleRect)
        CGContextSaveGState(context)
        placeholderRectanglePath.addClip()
        sh15_placeholderImage.drawInRect(CGRectMake(floor(placeholderRectangleRect.minX + 0.5), floor(placeholderRectangleRect.minY + 0.5), sh15_placeholderImage.size.width, sh15_placeholderImage.size.height))
        CGContextRestoreGState(context)


        //// PickedImageRectangle Drawing
        let pickedImageRectangleRect = CGRectMake(frame.minX + 38.98, frame.minY + 43.75, 751.02, 338.25)
        let pickedImageRectanglePath = UIBezierPath()
        pickedImageRectanglePath.moveToPoint(CGPointMake(frame.minX + 39, frame.minY + 101))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 47, frame.minY + 114), controlPoint1: CGPointMake(frame.minX + 39.04, frame.minY + 104.87), controlPoint2: CGPointMake(frame.minX + 47, frame.minY + 100))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 43, frame.minY + 149), controlPoint1: CGPointMake(frame.minX + 47, frame.minY + 122.64), controlPoint2: CGPointMake(frame.minX + 42.84, frame.minY + 134.69))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 51, frame.minY + 149), controlPoint1: CGPointMake(frame.minX + 43.03, frame.minY + 151.93), controlPoint2: CGPointMake(frame.minX + 46.97, frame.minY + 145.8))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 55, frame.minY + 165), controlPoint1: CGPointMake(frame.minX + 53.91, frame.minY + 151.32), controlPoint2: CGPointMake(frame.minX + 53.2, frame.minY + 158.16))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 61, frame.minY + 178), controlPoint1: CGPointMake(frame.minX + 56.67, frame.minY + 171.38), controlPoint2: CGPointMake(frame.minX + 60.95, frame.minY + 175.77))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 55, frame.minY + 180), controlPoint1: CGPointMake(frame.minX + 61.03, frame.minY + 179.27), controlPoint2: CGPointMake(frame.minX + 55.65, frame.minY + 176.5))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 54, frame.minY + 216), controlPoint1: CGPointMake(frame.minX + 53.42, frame.minY + 188.44), controlPoint2: CGPointMake(frame.minX + 54.53, frame.minY + 208.8))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 55, frame.minY + 267), controlPoint1: CGPointMake(frame.minX + 52.33, frame.minY + 238.7), controlPoint2: CGPointMake(frame.minX + 55.26, frame.minY + 256.59))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 55, frame.minY + 316), controlPoint1: CGPointMake(frame.minX + 54.52, frame.minY + 286.04), controlPoint2: CGPointMake(frame.minX + 55.48, frame.minY + 302.3))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 61, frame.minY + 336), controlPoint1: CGPointMake(frame.minX + 54.74, frame.minY + 323.34), controlPoint2: CGPointMake(frame.minX + 62.75, frame.minY + 330.5))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 51, frame.minY + 359), controlPoint1: CGPointMake(frame.minX + 54, frame.minY + 358), controlPoint2: CGPointMake(frame.minX + 51, frame.minY + 359))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 61, frame.minY + 365), controlPoint1: CGPointMake(frame.minX + 51, frame.minY + 359), controlPoint2: CGPointMake(frame.minX + 49, frame.minY + 363))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 94, frame.minY + 369), controlPoint1: CGPointMake(frame.minX + 66.44, frame.minY + 365.91), controlPoint2: CGPointMake(frame.minX + 80.46, frame.minY + 365.36))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 126, frame.minY + 382), controlPoint1: CGPointMake(frame.minX + 110.31, frame.minY + 373.39), controlPoint2: CGPointMake(frame.minX + 126, frame.minY + 382))
        pickedImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 131, frame.minY + 374))
        pickedImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 162, frame.minY + 372))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 187, frame.minY + 380), controlPoint1: CGPointMake(frame.minX + 162, frame.minY + 372), controlPoint2: CGPointMake(frame.minX + 173.75, frame.minY + 377.3))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 206, frame.minY + 380), controlPoint1: CGPointMake(frame.minX + 193.73, frame.minY + 381.37), controlPoint2: CGPointMake(frame.minX + 200.02, frame.minY + 382.18))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 217, frame.minY + 374), controlPoint1: CGPointMake(frame.minX + 209.9, frame.minY + 378.58), controlPoint2: CGPointMake(frame.minX + 213.94, frame.minY + 374))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 276, frame.minY + 380), controlPoint1: CGPointMake(frame.minX + 220.2, frame.minY + 374), controlPoint2: CGPointMake(frame.minX + 242.22, frame.minY + 380.11))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 315, frame.minY + 374), controlPoint1: CGPointMake(frame.minX + 287.66, frame.minY + 379.96), controlPoint2: CGPointMake(frame.minX + 300.86, frame.minY + 374.12))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 354, frame.minY + 380), controlPoint1: CGPointMake(frame.minX + 327.27, frame.minY + 373.89), controlPoint2: CGPointMake(frame.minX + 340.28, frame.minY + 380.1))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 395, frame.minY + 365), controlPoint1: CGPointMake(frame.minX + 371.53, frame.minY + 379.88), controlPoint2: CGPointMake(frame.minX + 375.82, frame.minY + 365.23))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 458, frame.minY + 369), controlPoint1: CGPointMake(frame.minX + 415.32, frame.minY + 364.75), controlPoint2: CGPointMake(frame.minX + 436.38, frame.minY + 368.95))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 499, frame.minY + 367), controlPoint1: CGPointMake(frame.minX + 469.88, frame.minY + 369.03), controlPoint2: CGPointMake(frame.minX + 486.97, frame.minY + 366.95))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 535, frame.minY + 373), controlPoint1: CGPointMake(frame.minX + 509.82, frame.minY + 367.05), controlPoint2: CGPointMake(frame.minX + 524.25, frame.minY + 372.89))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 560, frame.minY + 365), controlPoint1: CGPointMake(frame.minX + 546.03, frame.minY + 373.11), controlPoint2: CGPointMake(frame.minX + 549.22, frame.minY + 364.94))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 620, frame.minY + 374), controlPoint1: CGPointMake(frame.minX + 574.3, frame.minY + 365.08), controlPoint2: CGPointMake(frame.minX + 606.2, frame.minY + 373.77))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 620, frame.minY + 369), controlPoint1: CGPointMake(frame.minX + 623.62, frame.minY + 374.06), controlPoint2: CGPointMake(frame.minX + 616.45, frame.minY + 371.13))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 642, frame.minY + 365), controlPoint1: CGPointMake(frame.minX + 623.82, frame.minY + 366.71), controlPoint2: CGPointMake(frame.minX + 638.35, frame.minY + 365.19))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 668, frame.minY + 367), controlPoint1: CGPointMake(frame.minX + 648.88, frame.minY + 364.65), controlPoint2: CGPointMake(frame.minX + 661.58, frame.minY + 364.89))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 675, frame.minY + 372), controlPoint1: CGPointMake(frame.minX + 672.44, frame.minY + 368.46), controlPoint2: CGPointMake(frame.minX + 670.7, frame.minY + 372.01))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 758, frame.minY + 372), controlPoint1: CGPointMake(frame.minX + 708.23, frame.minY + 371.96), controlPoint2: CGPointMake(frame.minX + 758, frame.minY + 372))
        pickedImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 780, frame.minY + 359))
        pickedImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 780.57, frame.minY + 324.38))
        pickedImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 740, frame.minY + 330))
        pickedImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 780, frame.minY + 267))
        pickedImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 768, frame.minY + 257))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 782, frame.minY + 224), controlPoint1: CGPointMake(frame.minX + 768, frame.minY + 257), controlPoint2: CGPointMake(frame.minX + 779.11, frame.minY + 232.67))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 790, frame.minY + 184), controlPoint1: CGPointMake(frame.minX + 785, frame.minY + 215), controlPoint2: CGPointMake(frame.minX + 790, frame.minY + 187.56))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 745, frame.minY + 129), controlPoint1: CGPointMake(frame.minX + 790, frame.minY + 180.91), controlPoint2: CGPointMake(frame.minX + 745.95, frame.minY + 156.52))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 768, frame.minY + 101), controlPoint1: CGPointMake(frame.minX + 744.75, frame.minY + 121.74), controlPoint2: CGPointMake(frame.minX + 756.61, frame.minY + 108.41))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 786.43, frame.minY + 90.11), controlPoint1: CGPointMake(frame.minX + 776.82, frame.minY + 95.27), controlPoint2: CGPointMake(frame.minX + 785.67, frame.minY + 95.38))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 768, frame.minY + 62), controlPoint1: CGPointMake(frame.minX + 789.38, frame.minY + 69.48), controlPoint2: CGPointMake(frame.minX + 768, frame.minY + 62))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 703, frame.minY + 51), controlPoint1: CGPointMake(frame.minX + 768, frame.minY + 62), controlPoint2: CGPointMake(frame.minX + 735.23, frame.minY + 51.59))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 660, frame.minY + 56), controlPoint1: CGPointMake(frame.minX + 692.03, frame.minY + 50.8), controlPoint2: CGPointMake(frame.minX + 673.62, frame.minY + 56.16))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 622, frame.minY + 59), controlPoint1: CGPointMake(frame.minX + 656.59, frame.minY + 55.96), controlPoint2: CGPointMake(frame.minX + 641.34, frame.minY + 60.37))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 574.75, frame.minY + 50.29), controlPoint1: CGPointMake(frame.minX + 607.78, frame.minY + 57.99), controlPoint2: CGPointMake(frame.minX + 591.14, frame.minY + 52.23))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 521.37, frame.minY + 43.87), controlPoint1: CGPointMake(frame.minX + 555.05, frame.minY + 47.97), controlPoint2: CGPointMake(frame.minX + 535.71, frame.minY + 44.62))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 499, frame.minY + 45), controlPoint1: CGPointMake(frame.minX + 509.96, frame.minY + 43.27), controlPoint2: CGPointMake(frame.minX + 501.73, frame.minY + 45.05))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 474, frame.minY + 56), controlPoint1: CGPointMake(frame.minX + 494.12, frame.minY + 44.92), controlPoint2: CGPointMake(frame.minX + 485.04, frame.minY + 55.05))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 417, frame.minY + 51), controlPoint1: CGPointMake(frame.minX + 453.09, frame.minY + 57.81), controlPoint2: CGPointMake(frame.minX + 426.45, frame.minY + 51.08))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 400, frame.minY + 57), controlPoint1: CGPointMake(frame.minX + 407.2, frame.minY + 50.91), controlPoint2: CGPointMake(frame.minX + 412.7, frame.minY + 54.05))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 364, frame.minY + 57), controlPoint1: CGPointMake(frame.minX + 395.87, frame.minY + 57.96), controlPoint2: CGPointMake(frame.minX + 374.09, frame.minY + 56.19))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 344, frame.minY + 62), controlPoint1: CGPointMake(frame.minX + 350.92, frame.minY + 58.05), controlPoint2: CGPointMake(frame.minX + 349.09, frame.minY + 61.58))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 315, frame.minY + 68), controlPoint1: CGPointMake(frame.minX + 331.94, frame.minY + 63), controlPoint2: CGPointMake(frame.minX + 325.73, frame.minY + 68.82))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 282, frame.minY + 59), controlPoint1: CGPointMake(frame.minX + 301.33, frame.minY + 66.95), controlPoint2: CGPointMake(frame.minX + 293.56, frame.minY + 59.03))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 264, frame.minY + 62), controlPoint1: CGPointMake(frame.minX + 279.05, frame.minY + 58.99), controlPoint2: CGPointMake(frame.minX + 267.64, frame.minY + 61.66))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 253, frame.minY + 68), controlPoint1: CGPointMake(frame.minX + 260.06, frame.minY + 62.37), controlPoint2: CGPointMake(frame.minX + 257.43, frame.minY + 66.87))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 206, frame.minY + 68), controlPoint1: CGPointMake(frame.minX + 233.97, frame.minY + 72.83), controlPoint2: CGPointMake(frame.minX + 218.26, frame.minY + 68.18))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 186, frame.minY + 74), controlPoint1: CGPointMake(frame.minX + 201.86, frame.minY + 67.94), controlPoint2: CGPointMake(frame.minX + 194.68, frame.minY + 74.11))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 142, frame.minY + 67), controlPoint1: CGPointMake(frame.minX + 169.54, frame.minY + 73.8), controlPoint2: CGPointMake(frame.minX + 148.91, frame.minY + 67.28))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 94, frame.minY + 59), controlPoint1: CGPointMake(frame.minX + 118.99, frame.minY + 66.07), controlPoint2: CGPointMake(frame.minX + 107.43, frame.minY + 60.55))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 43, frame.minY + 56), controlPoint1: CGPointMake(frame.minX + 56.6, frame.minY + 54.67), controlPoint2: CGPointMake(frame.minX + 45.16, frame.minY + 53.53))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 39, frame.minY + 101), controlPoint1: CGPointMake(frame.minX + 41.4, frame.minY + 57.83), controlPoint2: CGPointMake(frame.minX + 38.74, frame.minY + 75))
        pickedImageRectanglePath.closePath()
        CGContextSaveGState(context)
        CGContextSetShadowWithColor(context, outerShadow.shadowOffset, outerShadow.shadowBlurRadius, (outerShadow.shadowColor as! UIColor).CGColor)
        CGContextBeginTransparencyLayer(context, nil)
        CGContextSaveGState(context)
        pickedImageRectanglePath.addClip()
        pickedImage.drawInRect(CGRectMake(floor(pickedImageRectangleRect.minX + 0.5), floor(pickedImageRectangleRect.minY + 0.5), pickedImage.size.width, pickedImage.size.height))
        CGContextRestoreGState(context)
        CGContextEndTransparencyLayer(context)
        CGContextRestoreGState(context)
    }

    //// Generated Images

    public class func imageOfSH15(frame frame: CGRect = CGRectMake(0, 0, 817, 461), pickedImage: UIImage = UIImage(named: "pickedImage.png")!) -> UIImage {
        UIGraphicsBeginImageContextWithOptions(frame.size, false, 0)
            SH15_PhotoFrame.drawSH15(frame: CGRectMake(0, 0, frame.size.width, frame.size.height), pickedImage: pickedImage)

        let imageOfSH15 = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return imageOfSH15
    }

}
