//
//  SH19_PhotoFrame.swift
//  Blagaprint
//
//  Created by Ivan Magda on 24.11.15.
//  Copyright (c) 2015 Blagaprint. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class SH19_PhotoFrame : NSObject {

    //// Drawing Methods

    public class func drawSH19(frame frame: CGRect = CGRectMake(0, 0, 529, 524), pickedImage: UIImage = UIImage()) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()


        //// Shadow Declarations
        let outerShadow = NSShadow()
        outerShadow.shadowColor = UIColor.darkGrayColor()
        outerShadow.shadowOffset = CGSizeMake(0.1, -0.1)
        outerShadow.shadowBlurRadius = 15

        //// Image Declarations
        let sH19_PlaceholderImage = UIImage(named: "sh19_placeholderImage.jpg")!

        //// PlaceholderRectangle Drawing
        let placeholderRectangleRect = CGRectMake(frame.minX, frame.minY, 529, 524)
        let placeholderRectanglePath = UIBezierPath(rect: placeholderRectangleRect)
        CGContextSaveGState(context)
        placeholderRectanglePath.addClip()
        sH19_PlaceholderImage.drawInRect(CGRectMake(floor(placeholderRectangleRect.minX + 0.5), floor(placeholderRectangleRect.minY + 0.5), sH19_PlaceholderImage.size.width, sH19_PlaceholderImage.size.height))
        CGContextRestoreGState(context)


        //// PickedImageRectangle Drawing
        let pickedImageRectangleRect = CGRectMake(frame.minX + 54.75, frame.minY + 42, 400, 400)
        let pickedImageRectanglePath = UIBezierPath()
        pickedImageRectanglePath.moveToPoint(CGPointMake(frame.minX + 63.97, frame.minY + 73.98))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 56, frame.minY + 127.96), controlPoint1: CGPointMake(frame.minX + 61.32, frame.minY + 78.41), controlPoint2: CGPointMake(frame.minX + 60.98, frame.minY + 98.97))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 56, frame.minY + 190.93), controlPoint1: CGPointMake(frame.minX + 52.59, frame.minY + 147.75), controlPoint2: CGPointMake(frame.minX + 64.97, frame.minY + 165.94))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 56, frame.minY + 208.92), controlPoint1: CGPointMake(frame.minX + 54.1, frame.minY + 196.21), controlPoint2: CGPointMake(frame.minX + 54.58, frame.minY + 202.42))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 56, frame.minY + 227.91), controlPoint1: CGPointMake(frame.minX + 57.38, frame.minY + 215.24), controlPoint2: CGPointMake(frame.minX + 54.2, frame.minY + 221.43))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 63.97, frame.minY + 247.9), controlPoint1: CGPointMake(frame.minX + 57.9, frame.minY + 234.78), controlPoint2: CGPointMake(frame.minX + 64.72, frame.minY + 241.92))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 59.98, frame.minY + 289.88), controlPoint1: CGPointMake(frame.minX + 62.55, frame.minY + 259.29), controlPoint2: CGPointMake(frame.minX + 60.77, frame.minY + 278.55))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 62.98, frame.minY + 304.29), controlPoint1: CGPointMake(frame.minX + 59.74, frame.minY + 293.45), controlPoint2: CGPointMake(frame.minX + 64.23, frame.minY + 295.1))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 66.97, frame.minY + 345.34), controlPoint1: CGPointMake(frame.minX + 59.99, frame.minY + 326.31), controlPoint2: CGPointMake(frame.minX + 67.14, frame.minY + 337.36))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 65.97, frame.minY + 375.37), controlPoint1: CGPointMake(frame.minX + 66.76, frame.minY + 355.48), controlPoint2: CGPointMake(frame.minX + 66.67, frame.minY + 365.98))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 66.97, frame.minY + 406.4), controlPoint1: CGPointMake(frame.minX + 65.29, frame.minY + 384.53), controlPoint2: CGPointMake(frame.minX + 66.98, frame.minY + 400.2))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 64.97, frame.minY + 439.8), controlPoint1: CGPointMake(frame.minX + 66.93, frame.minY + 433.83), controlPoint2: CGPointMake(frame.minX + 64.97, frame.minY + 439.8))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 79.92, frame.minY + 440.81), controlPoint1: CGPointMake(frame.minX + 64.97, frame.minY + 439.8), controlPoint2: CGPointMake(frame.minX + 71.96, frame.minY + 443.76))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 97.86, frame.minY + 429.81), controlPoint1: CGPointMake(frame.minX + 86.91, frame.minY + 438.22), controlPoint2: CGPointMake(frame.minX + 93.67, frame.minY + 430.75))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 113.81, frame.minY + 433.81), controlPoint1: CGPointMake(frame.minX + 98.83, frame.minY + 429.6), controlPoint2: CGPointMake(frame.minX + 107.32, frame.minY + 430.84))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 120.79, frame.minY + 436.81), controlPoint1: CGPointMake(frame.minX + 115.48, frame.minY + 434.57), controlPoint2: CGPointMake(frame.minX + 119.4, frame.minY + 435.66))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 124.78, frame.minY + 440.81), controlPoint1: CGPointMake(frame.minX + 122.65, frame.minY + 438.35), controlPoint2: CGPointMake(frame.minX + 122.01, frame.minY + 439.96))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 135.74, frame.minY + 440.81), controlPoint1: CGPointMake(frame.minX + 126.83, frame.minY + 441.43), controlPoint2: CGPointMake(frame.minX + 132.56, frame.minY + 440.76))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 136.74, frame.minY + 431.81), controlPoint1: CGPointMake(frame.minX + 137.27, frame.minY + 440.83), controlPoint2: CGPointMake(frame.minX + 136.74, frame.minY + 431.81))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 149.7, frame.minY + 431.81), controlPoint1: CGPointMake(frame.minX + 136.74, frame.minY + 431.81), controlPoint2: CGPointMake(frame.minX + 144.07, frame.minY + 431.81))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 165.65, frame.minY + 431.81), controlPoint1: CGPointMake(frame.minX + 154.95, frame.minY + 431.81), controlPoint2: CGPointMake(frame.minX + 160.87, frame.minY + 431.3))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 175.62, frame.minY + 433.81), controlPoint1: CGPointMake(frame.minX + 170.25, frame.minY + 432.3), controlPoint2: CGPointMake(frame.minX + 173.78, frame.minY + 433.8))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 193.56, frame.minY + 437.81), controlPoint1: CGPointMake(frame.minX + 181.73, frame.minY + 433.83), controlPoint2: CGPointMake(frame.minX + 187.71, frame.minY + 436.71))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 202.53, frame.minY + 438.81), controlPoint1: CGPointMake(frame.minX + 196.64, frame.minY + 438.38), controlPoint2: CGPointMake(frame.minX + 199.29, frame.minY + 439))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 207.52, frame.minY + 437.81), controlPoint1: CGPointMake(frame.minX + 204.02, frame.minY + 438.72), controlPoint2: CGPointMake(frame.minX + 205.87, frame.minY + 437.8))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 213.5, frame.minY + 441.81), controlPoint1: CGPointMake(frame.minX + 210.55, frame.minY + 437.83), controlPoint2: CGPointMake(frame.minX + 210.75, frame.minY + 440.57))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 218.19, frame.minY + 441.54), controlPoint1: CGPointMake(frame.minX + 214.69, frame.minY + 442.34), controlPoint2: CGPointMake(frame.minX + 216.35, frame.minY + 440.94))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 221.47, frame.minY + 441.81), controlPoint1: CGPointMake(frame.minX + 221.96, frame.minY + 442.77), controlPoint2: CGPointMake(frame.minX + 218.53, frame.minY + 441.03))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 229.45, frame.minY + 433.81), controlPoint1: CGPointMake(frame.minX + 223.27, frame.minY + 442.28), controlPoint2: CGPointMake(frame.minX + 225.82, frame.minY + 437.7))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 239.42, frame.minY + 426.81), controlPoint1: CGPointMake(frame.minX + 233.04, frame.minY + 429.97), controlPoint2: CGPointMake(frame.minX + 237.72, frame.minY + 426.81))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 255.37, frame.minY + 429.81), controlPoint1: CGPointMake(frame.minX + 240.69, frame.minY + 426.82), controlPoint2: CGPointMake(frame.minX + 247.8, frame.minY + 428.17))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 274.31, frame.minY + 434.81), controlPoint1: CGPointMake(frame.minX + 263.85, frame.minY + 431.66), controlPoint2: CGPointMake(frame.minX + 272.87, frame.minY + 434.82))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 280.29, frame.minY + 429.81), controlPoint1: CGPointMake(frame.minX + 276.09, frame.minY + 434.8), controlPoint2: CGPointMake(frame.minX + 278.41, frame.minY + 431.46))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 285.27, frame.minY + 426.81), controlPoint1: CGPointMake(frame.minX + 282.14, frame.minY + 428.19), controlPoint2: CGPointMake(frame.minX + 283.55, frame.minY + 427.26))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 301.22, frame.minY + 429.81), controlPoint1: CGPointMake(frame.minX + 289.44, frame.minY + 425.73), controlPoint2: CGPointMake(frame.minX + 297.12, frame.minY + 429.8))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 313.18, frame.minY + 432.81), controlPoint1: CGPointMake(frame.minX + 305.82, frame.minY + 429.82), controlPoint2: CGPointMake(frame.minX + 309.33, frame.minY + 431.28))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 328.14, frame.minY + 436.81), controlPoint1: CGPointMake(frame.minX + 317.89, frame.minY + 434.68), controlPoint2: CGPointMake(frame.minX + 322.89, frame.minY + 436.71))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 337.11, frame.minY + 432.81), controlPoint1: CGPointMake(frame.minX + 330.1, frame.minY + 436.85), controlPoint2: CGPointMake(frame.minX + 335.79, frame.minY + 434.4))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 337.11, frame.minY + 429.81), controlPoint1: CGPointMake(frame.minX + 338.28, frame.minY + 431.39), controlPoint2: CGPointMake(frame.minX + 335.05, frame.minY + 430.9))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 351.07, frame.minY + 426.81), controlPoint1: CGPointMake(frame.minX + 340.89, frame.minY + 427.82), controlPoint2: CGPointMake(frame.minX + 346.7, frame.minY + 427.03))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 355.05, frame.minY + 426.81), controlPoint1: CGPointMake(frame.minX + 352.68, frame.minY + 426.73), controlPoint2: CGPointMake(frame.minX + 353.94, frame.minY + 426.8))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 390.94, frame.minY + 426.81), controlPoint1: CGPointMake(frame.minX + 368.85, frame.minY + 426.98), controlPoint2: CGPointMake(frame.minX + 379.63, frame.minY + 425.92))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 393.93, frame.minY + 433.81), controlPoint1: CGPointMake(frame.minX + 394.03, frame.minY + 427.06), controlPoint2: CGPointMake(frame.minX + 391.35, frame.minY + 431.81))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 413.87, frame.minY + 437.81), controlPoint1: CGPointMake(frame.minX + 397.85, frame.minY + 436.84), controlPoint2: CGPointMake(frame.minX + 410.73, frame.minY + 437.49))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 434.8, frame.minY + 431.81), controlPoint1: CGPointMake(frame.minX + 433.09, frame.minY + 439.77), controlPoint2: CGPointMake(frame.minX + 434.8, frame.minY + 431.81))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 447.76, frame.minY + 416.82), controlPoint1: CGPointMake(frame.minX + 434.8, frame.minY + 431.81), controlPoint2: CGPointMake(frame.minX + 444.13, frame.minY + 430.6))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 447.76, frame.minY + 389.83), controlPoint1: CGPointMake(frame.minX + 449.18, frame.minY + 411.44), controlPoint2: CGPointMake(frame.minX + 446.23, frame.minY + 397.29))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 450.75, frame.minY + 368.84), controlPoint1: CGPointMake(frame.minX + 448.99, frame.minY + 383.83), controlPoint2: CGPointMake(frame.minX + 449.5, frame.minY + 376.55))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 454.74, frame.minY + 344.85), controlPoint1: CGPointMake(frame.minX + 452.02, frame.minY + 361.02), controlPoint2: CGPointMake(frame.minX + 454.01, frame.minY + 352.76))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 448.76, frame.minY + 334.86), controlPoint1: CGPointMake(frame.minX + 455.01, frame.minY + 341.94), controlPoint2: CGPointMake(frame.minX + 448.5, frame.minY + 337.85))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 447.76, frame.minY + 317.87), controlPoint1: CGPointMake(frame.minX + 449.18, frame.minY + 329.89), controlPoint2: CGPointMake(frame.minX + 448.23, frame.minY + 323.09))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 447.76, frame.minY + 301.87), controlPoint1: CGPointMake(frame.minX + 447.3, frame.minY + 312.69), controlPoint2: CGPointMake(frame.minX + 447.32, frame.minY + 307.09))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 453.74, frame.minY + 282.88), controlPoint1: CGPointMake(frame.minX + 448.3, frame.minY + 295.48), controlPoint2: CGPointMake(frame.minX + 453.28, frame.minY + 289.4))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 453.74, frame.minY + 272.89), controlPoint1: CGPointMake(frame.minX + 453.99, frame.minY + 279.37), controlPoint2: CGPointMake(frame.minX + 454.72, frame.minY + 276.36))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 450.75, frame.minY + 266.89), controlPoint1: CGPointMake(frame.minX + 453.22, frame.minY + 271.05), controlPoint2: CGPointMake(frame.minX + 450.63, frame.minY + 268.77))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 452.74, frame.minY + 258.9), controlPoint1: CGPointMake(frame.minX + 450.87, frame.minY + 265.13), controlPoint2: CGPointMake(frame.minX + 452.04, frame.minY + 261.58))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 453.74, frame.minY + 252.9), controlPoint1: CGPointMake(frame.minX + 453.43, frame.minY + 256.31), controlPoint2: CGPointMake(frame.minX + 453.64, frame.minY + 254.59))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 453.74, frame.minY + 242.9), controlPoint1: CGPointMake(frame.minX + 453.83, frame.minY + 251.39), controlPoint2: CGPointMake(frame.minX + 453.74, frame.minY + 252.15))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 453.74, frame.minY + 215.92), controlPoint1: CGPointMake(frame.minX + 453.74, frame.minY + 233.66), controlPoint2: CGPointMake(frame.minX + 454.73, frame.minY + 220.66))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 453.74, frame.minY + 212.92), controlPoint1: CGPointMake(frame.minX + 453.49, frame.minY + 214.71), controlPoint2: CGPointMake(frame.minX + 454.41, frame.minY + 213.99))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 450.75, frame.minY + 208.92), controlPoint1: CGPointMake(frame.minX + 453, frame.minY + 211.74), controlPoint2: CGPointMake(frame.minX + 450.68, frame.minY + 210.2))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 448.76, frame.minY + 196.93), controlPoint1: CGPointMake(frame.minX + 450.99, frame.minY + 204.45), controlPoint2: CGPointMake(frame.minX + 448.86, frame.minY + 200.56))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 450.75, frame.minY + 183.93), controlPoint1: CGPointMake(frame.minX + 448.63, frame.minY + 192.57), controlPoint2: CGPointMake(frame.minX + 450.51, frame.minY + 188.54))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 453.74, frame.minY + 148.95), controlPoint1: CGPointMake(frame.minX + 451.42, frame.minY + 171.22), controlPoint2: CGPointMake(frame.minX + 453.45, frame.minY + 157))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 450.75, frame.minY + 129.96), controlPoint1: CGPointMake(frame.minX + 454.06, frame.minY + 140.16), controlPoint2: CGPointMake(frame.minX + 450.88, frame.minY + 130.84))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 448.76, frame.minY + 115.96), controlPoint1: CGPointMake(frame.minX + 450.09, frame.minY + 125.35), controlPoint2: CGPointMake(frame.minX + 450, frame.minY + 121.13))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 445.77, frame.minY + 106.97), controlPoint1: CGPointMake(frame.minX + 448.11, frame.minY + 113.28), controlPoint2: CGPointMake(frame.minX + 446.19, frame.minY + 110.3))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 445.77, frame.minY + 90.98), controlPoint1: CGPointMake(frame.minX + 444.52, frame.minY + 97.22), controlPoint2: CGPointMake(frame.minX + 445.77, frame.minY + 90.98))
        pickedImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 442.78, frame.minY + 57.99))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 425.83, frame.minY + 49), controlPoint1: CGPointMake(frame.minX + 442.78, frame.minY + 57.99), controlPoint2: CGPointMake(frame.minX + 434.8, frame.minY + 51))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 385.96, frame.minY + 72.99), controlPoint1: CGPointMake(frame.minX + 424.55, frame.minY + 48.71), controlPoint2: CGPointMake(frame.minX + 399.3, frame.minY + 73.12))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 341.1, frame.minY + 57.99), controlPoint1: CGPointMake(frame.minX + 376.9, frame.minY + 72.89), controlPoint2: CGPointMake(frame.minX + 353.7, frame.minY + 58.55))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 341.1, frame.minY + 73.98), controlPoint1: CGPointMake(frame.minX + 333.73, frame.minY + 57.67), controlPoint2: CGPointMake(frame.minX + 349.24, frame.minY + 74.28))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 307.2, frame.minY + 57.99), controlPoint1: CGPointMake(frame.minX + 333.18, frame.minY + 73.7), controlPoint2: CGPointMake(frame.minX + 315.92, frame.minY + 58.44))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 296.24, frame.minY + 65.99), controlPoint1: CGPointMake(frame.minX + 305.07, frame.minY + 57.88), controlPoint2: CGPointMake(frame.minX + 303.84, frame.minY + 64.38))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 255.37, frame.minY + 57.99), controlPoint1: CGPointMake(frame.minX + 285.1, frame.minY + 68.35), controlPoint2: CGPointMake(frame.minX + 258.6, frame.minY + 58.14))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 229.45, frame.minY + 57.99), controlPoint1: CGPointMake(frame.minX + 247.95, frame.minY + 57.65), controlPoint2: CGPointMake(frame.minX + 236.69, frame.minY + 58.3))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 207.52, frame.minY + 53.99), controlPoint1: CGPointMake(frame.minX + 222.2, frame.minY + 57.69), controlPoint2: CGPointMake(frame.minX + 214.53, frame.minY + 54.28))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 175.62, frame.minY + 52), controlPoint1: CGPointMake(frame.minX + 202.81, frame.minY + 53.8), controlPoint2: CGPointMake(frame.minX + 189.15, frame.minY + 54.8))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 141.73, frame.minY + 42), controlPoint1: CGPointMake(frame.minX + 161.01, frame.minY + 48.97), controlPoint2: CGPointMake(frame.minX + 146.49, frame.minY + 42.14))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 132.75, frame.minY + 52), controlPoint1: CGPointMake(frame.minX + 135.96, frame.minY + 41.83), controlPoint2: CGPointMake(frame.minX + 137.7, frame.minY + 49.55))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 101.85, frame.minY + 57.99), controlPoint1: CGPointMake(frame.minX + 123.54, frame.minY + 56.56), controlPoint2: CGPointMake(frame.minX + 108.6, frame.minY + 57.45))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 74.94, frame.minY + 57.99), controlPoint1: CGPointMake(frame.minX + 70.39, frame.minY + 60.51), controlPoint2: CGPointMake(frame.minX + 74.94, frame.minY + 57.99))
        pickedImageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 63.97, frame.minY + 73.98), controlPoint1: CGPointMake(frame.minX + 74.94, frame.minY + 57.99), controlPoint2: CGPointMake(frame.minX + 75.93, frame.minY + 53.99))
        pickedImageRectanglePath.closePath()
        CGContextSaveGState(context)
        CGContextSetShadowWithColor(context, outerShadow.shadowOffset, outerShadow.shadowBlurRadius, (outerShadow.shadowColor as! UIColor).CGColor)
        CGContextBeginTransparencyLayer(context, nil)
        CGContextSaveGState(context)
        pickedImageRectanglePath.addClip()
        pickedImage.drawInRect(CGRectMake(floor(pickedImageRectangleRect.minX + 0.5), floor(pickedImageRectangleRect.minY + 0.44 + 0.5), pickedImage.size.width, pickedImage.size.height))
        CGContextRestoreGState(context)
        CGContextEndTransparencyLayer(context)
        CGContextRestoreGState(context)
    }

    //// Generated Images

    public class func imageOfSH19(frame frame: CGRect = CGRectMake(0, 0, 529, 524), pickedImage: UIImage = UIImage()) -> UIImage {
        UIGraphicsBeginImageContextWithOptions(frame.size, false, 0)
            SH19_PhotoFrame.drawSH19(frame: CGRectMake(0, 0, frame.size.width, frame.size.height), pickedImage: pickedImage)

        let imageOfSH19 = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return imageOfSH19
    }

}
