//
//  SH38_PhotoFrame.swift
//  Blagaprint
//
//  Created by Ivan Magda on 23.11.15.
//  Copyright (c) 2015 Blagaprint. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class SH38_PhotoFrame : NSObject {

    //// Drawing Methods

    public class func drawSH38(frame frame: CGRect = CGRectMake(0, 0, 462, 356), pickedImage: UIImage = UIImage()) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()


        //// Shadow Declarations
        let outerShadow = NSShadow()
        outerShadow.shadowColor = UIColor.blackColor()
        outerShadow.shadowOffset = CGSizeMake(0.1, -0.1)
        outerShadow.shadowBlurRadius = 10

        //// Image Declarations
        let placeholderImage = UIImage(named: "sh38_placeholderImage.jpg")!

        //// Placeholder Drawing
        let placeholderRect = CGRectMake(frame.minX, frame.minY, 462, 356)
        let placeholderPath = UIBezierPath(rect: placeholderRect)
        CGContextSaveGState(context)
        placeholderPath.addClip()
        placeholderImage.drawInRect(CGRectMake(floor(placeholderRect.minX + 0.5), floor(placeholderRect.minY + 0.5), placeholderImage.size.width, placeholderImage.size.height))
        CGContextRestoreGState(context)


        //// ImageRect Drawing
        let imageRectRect = CGRectMake(frame.minX + 89, frame.minY + 80, 282, 200)
        let imageRectPath = UIBezierPath()
        imageRectPath.moveToPoint(CGPointMake(frame.minX + 89, frame.minY + 120))
        imageRectPath.addLineToPoint(CGPointMake(frame.minX + 89.47, frame.minY + 134.43))
        imageRectPath.addLineToPoint(CGPointMake(frame.minX + 94, frame.minY + 134))
        imageRectPath.addLineToPoint(CGPointMake(frame.minX + 94, frame.minY + 142))
        imageRectPath.addLineToPoint(CGPointMake(frame.minX + 91, frame.minY + 150))
        imageRectPath.addLineToPoint(CGPointMake(frame.minX + 89.75, frame.minY + 159.73))
        imageRectPath.addLineToPoint(CGPointMake(frame.minX + 90, frame.minY + 183))
        imageRectPath.addLineToPoint(CGPointMake(frame.minX + 94, frame.minY + 187))
        imageRectPath.addLineToPoint(CGPointMake(frame.minX + 97, frame.minY + 195))
        imageRectPath.addLineToPoint(CGPointMake(frame.minX + 92, frame.minY + 210))
        imageRectPath.addLineToPoint(CGPointMake(frame.minX + 91, frame.minY + 220))
        imageRectPath.addLineToPoint(CGPointMake(frame.minX + 91, frame.minY + 234))
        imageRectPath.addLineToPoint(CGPointMake(frame.minX + 96, frame.minY + 234))
        imageRectPath.addLineToPoint(CGPointMake(frame.minX + 96, frame.minY + 275))
        imageRectPath.addLineToPoint(CGPointMake(frame.minX + 107, frame.minY + 275))
        imageRectPath.addCurveToPoint(CGPointMake(frame.minX + 121, frame.minY + 280), controlPoint1: CGPointMake(frame.minX + 107, frame.minY + 275), controlPoint2: CGPointMake(frame.minX + 117, frame.minY + 280))
        imageRectPath.addCurveToPoint(CGPointMake(frame.minX + 131.97, frame.minY + 274.05), controlPoint1: CGPointMake(frame.minX + 125, frame.minY + 280), controlPoint2: CGPointMake(frame.minX + 131.97, frame.minY + 274.05))
        imageRectPath.addLineToPoint(CGPointMake(frame.minX + 177, frame.minY + 272))
        imageRectPath.addLineToPoint(CGPointMake(frame.minX + 180.13, frame.minY + 270.39))
        imageRectPath.addLineToPoint(CGPointMake(frame.minX + 186, frame.minY + 270))
        imageRectPath.addCurveToPoint(CGPointMake(frame.minX + 200, frame.minY + 268), controlPoint1: CGPointMake(frame.minX + 186, frame.minY + 270), controlPoint2: CGPointMake(frame.minX + 193, frame.minY + 269))
        imageRectPath.addCurveToPoint(CGPointMake(frame.minX + 236, frame.minY + 269), controlPoint1: CGPointMake(frame.minX + 207, frame.minY + 267), controlPoint2: CGPointMake(frame.minX + 236, frame.minY + 269))
        imageRectPath.addLineToPoint(CGPointMake(frame.minX + 251, frame.minY + 260))
        imageRectPath.addLineToPoint(CGPointMake(frame.minX + 283, frame.minY + 263))
        imageRectPath.addLineToPoint(CGPointMake(frame.minX + 291, frame.minY + 260))
        imageRectPath.addLineToPoint(CGPointMake(frame.minX + 311.62, frame.minY + 260.3))
        imageRectPath.addLineToPoint(CGPointMake(frame.minX + 371, frame.minY + 255))
        imageRectPath.addCurveToPoint(CGPointMake(frame.minX + 367, frame.minY + 200), controlPoint1: CGPointMake(frame.minX + 371, frame.minY + 255), controlPoint2: CGPointMake(frame.minX + 369.53, frame.minY + 224.63))
        imageRectPath.addCurveToPoint(CGPointMake(frame.minX + 361, frame.minY + 187), controlPoint1: CGPointMake(frame.minX + 366.38, frame.minY + 194), controlPoint2: CGPointMake(frame.minX + 361, frame.minY + 187.78))
        imageRectPath.addCurveToPoint(CGPointMake(frame.minX + 364, frame.minY + 177), controlPoint1: CGPointMake(frame.minX + 361, frame.minY + 183), controlPoint2: CGPointMake(frame.minX + 364, frame.minY + 177))
        imageRectPath.addLineToPoint(CGPointMake(frame.minX + 367, frame.minY + 160))
        imageRectPath.addLineToPoint(CGPointMake(frame.minX + 367, frame.minY + 154))
        imageRectPath.addLineToPoint(CGPointMake(frame.minX + 364, frame.minY + 146))
        imageRectPath.addLineToPoint(CGPointMake(frame.minX + 367, frame.minY + 115))
        imageRectPath.addLineToPoint(CGPointMake(frame.minX + 367, frame.minY + 106))
        imageRectPath.addLineToPoint(CGPointMake(frame.minX + 371, frame.minY + 98))
        imageRectPath.addLineToPoint(CGPointMake(frame.minX + 371, frame.minY + 83))
        imageRectPath.addLineToPoint(CGPointMake(frame.minX + 331, frame.minY + 80))
        imageRectPath.addCurveToPoint(CGPointMake(frame.minX + 326, frame.minY + 83), controlPoint1: CGPointMake(frame.minX + 331, frame.minY + 80), controlPoint2: CGPointMake(frame.minX + 329.21, frame.minY + 82.72))
        imageRectPath.addCurveToPoint(CGPointMake(frame.minX + 306, frame.minY + 82), controlPoint1: CGPointMake(frame.minX + 321.77, frame.minY + 83.37), controlPoint2: CGPointMake(frame.minX + 313.02, frame.minY + 81.87))
        imageRectPath.addCurveToPoint(CGPointMake(frame.minX + 287, frame.minY + 85), controlPoint1: CGPointMake(frame.minX + 298.92, frame.minY + 82.13), controlPoint2: CGPointMake(frame.minX + 293.56, frame.minY + 83.91))
        imageRectPath.addCurveToPoint(CGPointMake(frame.minX + 283, frame.minY + 87), controlPoint1: CGPointMake(frame.minX + 282.5, frame.minY + 85.75), controlPoint2: CGPointMake(frame.minX + 285.24, frame.minY + 86.84))
        imageRectPath.addCurveToPoint(CGPointMake(frame.minX + 245, frame.minY + 85), controlPoint1: CGPointMake(frame.minX + 272.2, frame.minY + 87.76), controlPoint2: CGPointMake(frame.minX + 257.48, frame.minY + 84.86))
        imageRectPath.addCurveToPoint(CGPointMake(frame.minX + 240.4, frame.minY + 87.24), controlPoint1: CGPointMake(frame.minX + 243.46, frame.minY + 85.02), controlPoint2: CGPointMake(frame.minX + 241.93, frame.minY + 87.11))
        imageRectPath.addCurveToPoint(CGPointMake(frame.minX + 227, frame.minY + 87), controlPoint1: CGPointMake(frame.minX + 235.81, frame.minY + 87.64), controlPoint2: CGPointMake(frame.minX + 231.3, frame.minY + 86.45))
        imageRectPath.addCurveToPoint(CGPointMake(frame.minX + 201, frame.minY + 90), controlPoint1: CGPointMake(frame.minX + 218.22, frame.minY + 88.13), controlPoint2: CGPointMake(frame.minX + 209.96, frame.minY + 89.05))
        imageRectPath.addCurveToPoint(CGPointMake(frame.minX + 195, frame.minY + 93), controlPoint1: CGPointMake(frame.minX + 197.3, frame.minY + 90.39), controlPoint2: CGPointMake(frame.minX + 197.45, frame.minY + 92.36))
        imageRectPath.addCurveToPoint(CGPointMake(frame.minX + 186, frame.minY + 93), controlPoint1: CGPointMake(frame.minX + 193.11, frame.minY + 93.5), controlPoint2: CGPointMake(frame.minX + 188.67, frame.minY + 92.68))
        imageRectPath.addCurveToPoint(CGPointMake(frame.minX + 171, frame.minY + 103), controlPoint1: CGPointMake(frame.minX + 178.77, frame.minY + 93.85), controlPoint2: CGPointMake(frame.minX + 177.53, frame.minY + 102.37))
        imageRectPath.addCurveToPoint(CGPointMake(frame.minX + 141, frame.minY + 98), controlPoint1: CGPointMake(frame.minX + 159.55, frame.minY + 104.11), controlPoint2: CGPointMake(frame.minX + 150.38, frame.minY + 99.92))
        imageRectPath.addCurveToPoint(CGPointMake(frame.minX + 111, frame.minY + 93), controlPoint1: CGPointMake(frame.minX + 124.98, frame.minY + 94.72), controlPoint2: CGPointMake(frame.minX + 111.85, frame.minY + 92.36))
        imageRectPath.addCurveToPoint(CGPointMake(frame.minX + 89, frame.minY + 120), controlPoint1: CGPointMake(frame.minX + 107, frame.minY + 96), controlPoint2: CGPointMake(frame.minX + 89, frame.minY + 120))
        imageRectPath.closePath()
        CGContextSaveGState(context)
        CGContextSetShadowWithColor(context, outerShadow.shadowOffset, outerShadow.shadowBlurRadius, (outerShadow.shadowColor as! UIColor).CGColor)
        CGContextBeginTransparencyLayer(context, nil)
        CGContextSaveGState(context)
        imageRectPath.addClip()
        pickedImage.drawInRect(CGRectMake(floor(imageRectRect.minX + 0.5), floor(imageRectRect.minY + 0.5), pickedImage.size.width, pickedImage.size.height))
        CGContextRestoreGState(context)
        CGContextEndTransparencyLayer(context)
        CGContextRestoreGState(context)
    }

    //// Generated Images

    public class func imageOfSH38(frame frame: CGRect = CGRectMake(0, 0, 462, 356), pickedImage: UIImage = UIImage()) -> UIImage {
        UIGraphicsBeginImageContextWithOptions(frame.size, false, 0)
            SH38_PhotoFrame.drawSH38(frame: CGRectMake(0, 0, frame.size.width, frame.size.height), pickedImage: pickedImage)

        let imageOfSH38 = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return imageOfSH38
    }

}
