//
//  SH38_PhotoFrame.swift
//  Blagaprint
//
//  Created by Ivan Magda on 21.11.15.
//  Copyright (c) 2015 Blagaprint. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class SH38_PhotoFrame : NSObject {

    //// Drawing Methods

    public class func drawSH38(frame frame: CGRect = CGRectMake(0, 0, 320, 250), pickedImage: UIImage = UIImage(named: "pickedImage.png")!) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()


        //// Image Declarations
        let placeholderImage = UIImage(named: "placeholderImage.jpg") ?? UIImage()

        //// Placeholder Drawing
        let placeholderRect = CGRectMake(frame.minX + 8, frame.minY + 9, 304, 231)
        let placeholderPath = UIBezierPath(rect: placeholderRect)
        CGContextSaveGState(context)
        placeholderPath.addClip()
        placeholderImage.drawInRect(CGRectMake(floor(placeholderRect.minX + 0.5), floor(placeholderRect.minY - 2 + 0.5), placeholderImage.size.width, placeholderImage.size.height))
        CGContextRestoreGState(context)


        //// PickingImageRectangle Drawing
        let pickingImageRectangleRect = CGRectMake(frame.minX + 67, frame.minY + 63, 189, 132)
        let pickingImageRectanglePath = UIBezierPath()
        pickingImageRectanglePath.moveToPoint(CGPointMake(frame.minX + 74, frame.minY + 80))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 67, frame.minY + 89))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 67, frame.minY + 99))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 69, frame.minY + 100))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 69, frame.minY + 110))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 68, frame.minY + 113))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 67, frame.minY + 117))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 67, frame.minY + 122))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 67, frame.minY + 133))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 69, frame.minY + 133))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 69, frame.minY + 141))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 68, frame.minY + 144))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 68, frame.minY + 150))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 68, frame.minY + 151))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 67, frame.minY + 151))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 67, frame.minY + 158))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 68.35, frame.minY + 157.85))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 68, frame.minY + 167))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 71, frame.minY + 167))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 70, frame.minY + 176))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 69, frame.minY + 178))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 70, frame.minY + 181))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 71, frame.minY + 183))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 71, frame.minY + 190))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 70, frame.minY + 194))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 77, frame.minY + 195))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 84, frame.minY + 195))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 92, frame.minY + 194))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 106, frame.minY + 194))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 108, frame.minY + 192))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 139.29, frame.minY + 191.56))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 141, frame.minY + 190))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 165, frame.minY + 190))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 176, frame.minY + 185))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 206, frame.minY + 185))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 218, frame.minY + 185))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 233, frame.minY + 183))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 245, frame.minY + 181))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 250, frame.minY + 180))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 250, frame.minY + 176))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 252, frame.minY + 174))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 256, frame.minY + 178))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 255, frame.minY + 135))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 255, frame.minY + 110))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 252, frame.minY + 110))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 252, frame.minY + 106))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 253, frame.minY + 106))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 253, frame.minY + 100))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 255, frame.minY + 90))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 253, frame.minY + 87))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 253, frame.minY + 83))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 255, frame.minY + 82))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 255, frame.minY + 80))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 256, frame.minY + 77))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 256, frame.minY + 71))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 256, frame.minY + 65))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 235, frame.minY + 63))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 210, frame.minY + 64))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 199, frame.minY + 65))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 190, frame.minY + 66))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 184, frame.minY + 65))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 170, frame.minY + 65))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 170, frame.minY + 67))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 164, frame.minY + 67))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 162, frame.minY + 66))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 151, frame.minY + 66))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 150, frame.minY + 68))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 139, frame.minY + 67))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 141, frame.minY + 70))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 138, frame.minY + 72))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 130, frame.minY + 71))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 128, frame.minY + 74))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 125, frame.minY + 77))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 120, frame.minY + 77))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 108, frame.minY + 77))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 103, frame.minY + 77))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 100, frame.minY + 72))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 92, frame.minY + 71))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 82, frame.minY + 70))
        pickingImageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 74, frame.minY + 80))
        pickingImageRectanglePath.closePath()
        CGContextSaveGState(context)
        pickingImageRectanglePath.addClip()
        pickedImage.drawInRect(CGRectMake(floor(pickingImageRectangleRect.minX + 0.5), floor(pickingImageRectangleRect.minY + 0.5), pickedImage.size.width, pickedImage.size.height))
        CGContextRestoreGState(context)
    }

    //// Generated Images

    public class func imageOfSH38(frame frame: CGRect = CGRectMake(0, 0, 320, 250), pickedImage: UIImage = UIImage(named: "pickedImage.png")!) -> UIImage {
        UIGraphicsBeginImageContextWithOptions(frame.size, false, 0)
            SH38_PhotoFrame.drawSH38(frame: CGRectMake(0, 0, frame.size.width, frame.size.height), pickedImage: pickedImage)

        let imageOfSH38 = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return imageOfSH38
    }

}
