//
//  SH3_PhotoFrame.swift
//  Blagaprint
//
//  Created by Ivan Magda on 24.11.15.
//  Copyright (c) 2015 Blagaprint. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class SH3_PhotoFrame : NSObject {

    //// Drawing Methods

    public class func drawSH3(frame frame: CGRect = CGRectMake(0, 0, 474, 372), pickedImage: UIImage = UIImage(named: "pickedImage.png")!) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()


        //// Shadow Declarations
        let shadow = NSShadow()
        shadow.shadowColor = UIColor.blackColor()
        shadow.shadowOffset = CGSizeMake(0.1, -0.1)
        shadow.shadowBlurRadius = 10

        //// Image Declarations
        let sh3_placeholderImage = UIImage(named: "sh3_placeholderImage.jpg")!

        //// PlaceholderRectangle Drawing
        let placeholderRectangleRect = CGRectMake(frame.minX, frame.minY, 474, 372)
        let placeholderRectanglePath = UIBezierPath(rect: placeholderRectangleRect)
        CGContextSaveGState(context)
        placeholderRectanglePath.addClip()
        sh3_placeholderImage.drawInRect(CGRectMake(floor(placeholderRectangleRect.minX + 0.5), floor(placeholderRectangleRect.minY + 0.5), sh3_placeholderImage.size.width, sh3_placeholderImage.size.height))
        CGContextRestoreGState(context)


        //// ImageRectangle Drawing
        let imageRectangleRect = CGRectMake(frame.minX + 37.8, frame.minY + 27.94, 402, 286)
        let imageRectanglePath = UIBezierPath()
        imageRectanglePath.moveToPoint(CGPointMake(frame.minX + 61.85, frame.minY + 42.71))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 58.99, frame.minY + 48), controlPoint1: CGPointMake(frame.minX + 60.9, frame.minY + 44.1), controlPoint2: CGPointMake(frame.minX + 60.65, frame.minY + 45.84))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 53.99, frame.minY + 55.99), controlPoint1: CGPointMake(frame.minX + 57.29, frame.minY + 50.19), controlPoint2: CGPointMake(frame.minX + 56.64, frame.minY + 52.87))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 46, frame.minY + 65.99), controlPoint1: CGPointMake(frame.minX + 51.54, frame.minY + 58.9), controlPoint2: CGPointMake(frame.minX + 47.07, frame.minY + 62.18))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 47.99, frame.minY + 69.99), controlPoint1: CGPointMake(frame.minX + 45.34, frame.minY + 68.31), controlPoint2: CGPointMake(frame.minX + 46.38, frame.minY + 66.98))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 50.99, frame.minY + 82.99), controlPoint1: CGPointMake(frame.minX + 49.55, frame.minY + 72.89), controlPoint2: CGPointMake(frame.minX + 51.7, frame.minY + 80.12))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 47, frame.minY + 98.99), controlPoint1: CGPointMake(frame.minX + 50, frame.minY + 87.03), controlPoint2: CGPointMake(frame.minX + 48.41, frame.minY + 92.62))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 46, frame.minY + 106.98), controlPoint1: CGPointMake(frame.minX + 46.43, frame.minY + 101.51), controlPoint2: CGPointMake(frame.minX + 47.06, frame.minY + 104.36))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 41.05, frame.minY + 118.85), controlPoint1: CGPointMake(frame.minX + 44.35, frame.minY + 111.03), controlPoint2: CGPointMake(frame.minX + 42.82, frame.minY + 115.17))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 38, frame.minY + 124.98), controlPoint1: CGPointMake(frame.minX + 39.95, frame.minY + 121.12), controlPoint2: CGPointMake(frame.minX + 38.14, frame.minY + 123.2))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 44, frame.minY + 144.98), controlPoint1: CGPointMake(frame.minX + 37.34, frame.minY + 133.17), controlPoint2: CGPointMake(frame.minX + 43.98, frame.minY + 135.22))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 38, frame.minY + 169.97), controlPoint1: CGPointMake(frame.minX + 44.01, frame.minY + 150.85), controlPoint2: CGPointMake(frame.minX + 36.47, frame.minY + 164.4))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 44, frame.minY + 179.97), controlPoint1: CGPointMake(frame.minX + 39, frame.minY + 173.61), controlPoint2: CGPointMake(frame.minX + 40.49, frame.minY + 176.89))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 47.99, frame.minY + 184.97), controlPoint1: CGPointMake(frame.minX + 45.93, frame.minY + 181.66), controlPoint2: CGPointMake(frame.minX + 48.03, frame.minY + 183.11))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 44, frame.minY + 190.97), controlPoint1: CGPointMake(frame.minX + 47.9, frame.minY + 189.41), controlPoint2: CGPointMake(frame.minX + 46.03, frame.minY + 188.72))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 43, frame.minY + 204.96), controlPoint1: CGPointMake(frame.minX + 42.34, frame.minY + 192.8), controlPoint2: CGPointMake(frame.minX + 42.33, frame.minY + 201.52))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 44, frame.minY + 222.96), controlPoint1: CGPointMake(frame.minX + 43.88, frame.minY + 209.54), controlPoint2: CGPointMake(frame.minX + 40.65, frame.minY + 216.42))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 56.99, frame.minY + 235.96), controlPoint1: CGPointMake(frame.minX + 46.54, frame.minY + 227.92), controlPoint2: CGPointMake(frame.minX + 56.96, frame.minY + 232.73))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 58.99, frame.minY + 246.95), controlPoint1: CGPointMake(frame.minX + 57.01, frame.minY + 237.97), controlPoint2: CGPointMake(frame.minX + 58.97, frame.minY + 245))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 62.99, frame.minY + 252.95), controlPoint1: CGPointMake(frame.minX + 59.05, frame.minY + 253.07), controlPoint2: CGPointMake(frame.minX + 61.83, frame.minY + 248.64))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 62.99, frame.minY + 278.95), controlPoint1: CGPointMake(frame.minX + 64.61, frame.minY + 258.97), controlPoint2: CGPointMake(frame.minX + 62.77, frame.minY + 273.2))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 71.98, frame.minY + 299.94), controlPoint1: CGPointMake(frame.minX + 63.46, frame.minY + 291.74), controlPoint2: CGPointMake(frame.minX + 71.98, frame.minY + 299.94))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 85.97, frame.minY + 305.94), controlPoint1: CGPointMake(frame.minX + 71.98, frame.minY + 299.94), controlPoint2: CGPointMake(frame.minX + 73.56, frame.minY + 304.48))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 114.96, frame.minY + 304.94), controlPoint1: CGPointMake(frame.minX + 92.39, frame.minY + 306.7), controlPoint2: CGPointMake(frame.minX + 103.82, frame.minY + 304.3))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 140.94, frame.minY + 302.94), controlPoint1: CGPointMake(frame.minX + 122.47, frame.minY + 305.37), controlPoint2: CGPointMake(frame.minX + 130.89, frame.minY + 302.21))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 152.03, frame.minY + 304.96), controlPoint1: CGPointMake(frame.minX + 144.6, frame.minY + 303.21), controlPoint2: CGPointMake(frame.minX + 148.33, frame.minY + 304.49))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 165.93, frame.minY + 306.94), controlPoint1: CGPointMake(frame.minX + 156.77, frame.minY + 305.55), controlPoint2: CGPointMake(frame.minX + 161.47, frame.minY + 305.43))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 178.92, frame.minY + 309.94), controlPoint1: CGPointMake(frame.minX + 169.48, frame.minY + 308.14), controlPoint2: CGPointMake(frame.minX + 175.49, frame.minY + 308.25))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 186.92, frame.minY + 313.94), controlPoint1: CGPointMake(frame.minX + 182.3, frame.minY + 311.6), controlPoint2: CGPointMake(frame.minX + 183.09, frame.minY + 313.84))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 193.23, frame.minY + 310.09), controlPoint1: CGPointMake(frame.minX + 189.03, frame.minY + 314), controlPoint2: CGPointMake(frame.minX + 191.13, frame.minY + 311.56))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 199.91, frame.minY + 308.94), controlPoint1: CGPointMake(frame.minX + 195.46, frame.minY + 308.51), controlPoint2: CGPointMake(frame.minX + 197.69, frame.minY + 308.89))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 191.92, frame.minY + 297.94), controlPoint1: CGPointMake(frame.minX + 201.97, frame.minY + 308.99), controlPoint2: CGPointMake(frame.minX + 189.85, frame.minY + 297.89))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 207.53, frame.minY + 302.85), controlPoint1: CGPointMake(frame.minX + 197.63, frame.minY + 298.1), controlPoint2: CGPointMake(frame.minX + 201.25, frame.minY + 300.36))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 214.91, frame.minY + 305.94), controlPoint1: CGPointMake(frame.minX + 209.27, frame.minY + 303.54), controlPoint2: CGPointMake(frame.minX + 213.05, frame.minY + 305.25))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 226.9, frame.minY + 310.94), controlPoint1: CGPointMake(frame.minX + 219.32, frame.minY + 307.58), controlPoint2: CGPointMake(frame.minX + 222.32, frame.minY + 309.84))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 240.89, frame.minY + 310.94), controlPoint1: CGPointMake(frame.minX + 231.33, frame.minY + 312.01), controlPoint2: CGPointMake(frame.minX + 237.35, frame.minY + 310.95))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 255.88, frame.minY + 307.94), controlPoint1: CGPointMake(frame.minX + 242.65, frame.minY + 310.94), controlPoint2: CGPointMake(frame.minX + 250.14, frame.minY + 310.56))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 259.88, frame.minY + 302.94), controlPoint1: CGPointMake(frame.minX + 258.04, frame.minY + 306.96), controlPoint2: CGPointMake(frame.minX + 257.53, frame.minY + 303.82))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 273.87, frame.minY + 299.94), controlPoint1: CGPointMake(frame.minX + 265.25, frame.minY + 300.95), controlPoint2: CGPointMake(frame.minX + 272.43, frame.minY + 299.95))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 281.87, frame.minY + 299.94), controlPoint1: CGPointMake(frame.minX + 276.66, frame.minY + 299.94), controlPoint2: CGPointMake(frame.minX + 279.19, frame.minY + 299.95))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 286.87, frame.minY + 300.94), controlPoint1: CGPointMake(frame.minX + 287.08, frame.minY + 299.94), controlPoint2: CGPointMake(frame.minX + 282.02, frame.minY + 300.95))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 304.86, frame.minY + 302.94), controlPoint1: CGPointMake(frame.minX + 293.17, frame.minY + 300.93), controlPoint2: CGPointMake(frame.minX + 299.32, frame.minY + 302.98))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 308.59, frame.minY + 300.47), controlPoint1: CGPointMake(frame.minX + 307.73, frame.minY + 302.92), controlPoint2: CGPointMake(frame.minX + 306.77, frame.minY + 301.76))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 318.85, frame.minY + 296.94), controlPoint1: CGPointMake(frame.minX + 310.92, frame.minY + 298.82), controlPoint2: CGPointMake(frame.minX + 315.9, frame.minY + 296.95))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 335.84, frame.minY + 299.94), controlPoint1: CGPointMake(frame.minX + 326, frame.minY + 296.93), controlPoint2: CGPointMake(frame.minX + 331.6, frame.minY + 299.94))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 345.84, frame.minY + 293.94), controlPoint1: CGPointMake(frame.minX + 341.23, frame.minY + 299.94), controlPoint2: CGPointMake(frame.minX + 340.81, frame.minY + 295.28))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 359.11, frame.minY + 292.54), controlPoint1: CGPointMake(frame.minX + 349.84, frame.minY + 292.88), controlPoint2: CGPointMake(frame.minX + 354.94, frame.minY + 293.06))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 366.82, frame.minY + 290.95), controlPoint1: CGPointMake(frame.minX + 363.29, frame.minY + 292.02), controlPoint2: CGPointMake(frame.minX + 366.54, frame.minY + 290.81))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 396.81, frame.minY + 297.94), controlPoint1: CGPointMake(frame.minX + 370.82, frame.minY + 292.95), controlPoint2: CGPointMake(frame.minX + 396.81, frame.minY + 297.94))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 409.03, frame.minY + 290.74), controlPoint1: CGPointMake(frame.minX + 396.81, frame.minY + 297.94), controlPoint2: CGPointMake(frame.minX + 403.86, frame.minY + 295.43))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 412.92, frame.minY + 284.17), controlPoint1: CGPointMake(frame.minX + 411.08, frame.minY + 288.88), controlPoint2: CGPointMake(frame.minX + 411.14, frame.minY + 286.69))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 413.8, frame.minY + 277.95), controlPoint1: CGPointMake(frame.minX + 414.26, frame.minY + 282.28), controlPoint2: CGPointMake(frame.minX + 412.58, frame.minY + 280.2))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 417.63, frame.minY + 272.08), controlPoint1: CGPointMake(frame.minX + 414.63, frame.minY + 276.42), controlPoint2: CGPointMake(frame.minX + 416.58, frame.minY + 274.29))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 418.31, frame.minY + 266.88), controlPoint1: CGPointMake(frame.minX + 418.47, frame.minY + 270.32), controlPoint2: CGPointMake(frame.minX + 417.36, frame.minY + 268.5))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 421.8, frame.minY + 258.95), controlPoint1: CGPointMake(frame.minX + 420.16, frame.minY + 263.71), controlPoint2: CGPointMake(frame.minX + 422.45, frame.minY + 261.54))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 412.8, frame.minY + 243.96), controlPoint1: CGPointMake(frame.minX + 419.94, frame.minY + 251.6), controlPoint2: CGPointMake(frame.minX + 412.03, frame.minY + 252.79))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 415.81, frame.minY + 238.74), controlPoint1: CGPointMake(frame.minX + 412.92, frame.minY + 242.58), controlPoint2: CGPointMake(frame.minX + 415.29, frame.minY + 240.17))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 418.8, frame.minY + 227.96), controlPoint1: CGPointMake(frame.minX + 417.11, frame.minY + 235.19), controlPoint2: CGPointMake(frame.minX + 417.32, frame.minY + 231.51))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 426.79, frame.minY + 209.96), controlPoint1: CGPointMake(frame.minX + 421.31, frame.minY + 221.94), controlPoint2: CGPointMake(frame.minX + 422.71, frame.minY + 216.15))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 427.79, frame.minY + 204.96), controlPoint1: CGPointMake(frame.minX + 427.78, frame.minY + 208.46), controlPoint2: CGPointMake(frame.minX + 426.85, frame.minY + 206.5))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 431.9, frame.minY + 200.7), controlPoint1: CGPointMake(frame.minX + 428.71, frame.minY + 203.47), controlPoint2: CGPointMake(frame.minX + 431.29, frame.minY + 202.08))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 434.79, frame.minY + 196.96), controlPoint1: CGPointMake(frame.minX + 432.43, frame.minY + 199.48), controlPoint2: CGPointMake(frame.minX + 433.98, frame.minY + 198.26))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 437.48, frame.minY + 190.7), controlPoint1: CGPointMake(frame.minX + 436.11, frame.minY + 194.84), controlPoint2: CGPointMake(frame.minX + 436.5, frame.minY + 192.77))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 439.79, frame.minY + 184.97), controlPoint1: CGPointMake(frame.minX + 438.38, frame.minY + 188.8), controlPoint2: CGPointMake(frame.minX + 439.94, frame.minY + 186.9))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 426.79, frame.minY + 169.97), controlPoint1: CGPointMake(frame.minX + 439.29, frame.minY + 178.64), controlPoint2: CGPointMake(frame.minX + 431.97, frame.minY + 174.15))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 416.8, frame.minY + 153.97), controlPoint1: CGPointMake(frame.minX + 420.89, frame.minY + 165.21), controlPoint2: CGPointMake(frame.minX + 417.06, frame.minY + 160.83))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 420.27, frame.minY + 139.33), controlPoint1: CGPointMake(frame.minX + 416.57, frame.minY + 148.07), controlPoint2: CGPointMake(frame.minX + 419.28, frame.minY + 143.5))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 421.8, frame.minY + 124.98), controlPoint1: CGPointMake(frame.minX + 421.41, frame.minY + 134.53), controlPoint2: CGPointMake(frame.minX + 420.92, frame.minY + 130.23))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 421.8, frame.minY + 106.98), controlPoint1: CGPointMake(frame.minX + 422.59, frame.minY + 120.23), controlPoint2: CGPointMake(frame.minX + 421.8, frame.minY + 111.49))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 426.79, frame.minY + 96.99), controlPoint1: CGPointMake(frame.minX + 421.79, frame.minY + 103.25), controlPoint2: CGPointMake(frame.minX + 426.77, frame.minY + 100.13))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 430.79, frame.minY + 75.99), controlPoint1: CGPointMake(frame.minX + 426.83, frame.minY + 92.12), controlPoint2: CGPointMake(frame.minX + 430.74, frame.minY + 79.03))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 434.79, frame.minY + 69.99), controlPoint1: CGPointMake(frame.minX + 430.85, frame.minY + 72.28), controlPoint2: CGPointMake(frame.minX + 434.79, frame.minY + 70.36))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 431.55, frame.minY + 65.97), controlPoint1: CGPointMake(frame.minX + 434.79, frame.minY + 65.99), controlPoint2: CGPointMake(frame.minX + 431.55, frame.minY + 65.97))
        imageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 430.68, frame.minY + 62.62))
        imageRectanglePath.addLineToPoint(CGPointMake(frame.minX + 431.79, frame.minY + 33))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 407.8, frame.minY + 28), controlPoint1: CGPointMake(frame.minX + 431.79, frame.minY + 33), controlPoint2: CGPointMake(frame.minX + 419.71, frame.minY + 27.31))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 396.38, frame.minY + 33.47), controlPoint1: CGPointMake(frame.minX + 403.9, frame.minY + 28.23), controlPoint2: CGPointMake(frame.minX + 400.31, frame.minY + 31.79))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 380.2, frame.minY + 35.83), controlPoint1: CGPointMake(frame.minX + 391.8, frame.minY + 35.42), controlPoint2: CGPointMake(frame.minX + 386.74, frame.minY + 35.53))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 359.83, frame.minY + 35), controlPoint1: CGPointMake(frame.minX + 373.75, frame.minY + 36.12), controlPoint2: CGPointMake(frame.minX + 366.91, frame.minY + 34.5))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 342.54, frame.minY + 40.07), controlPoint1: CGPointMake(frame.minX + 353.45, frame.minY + 35.44), controlPoint2: CGPointMake(frame.minX + 348.16, frame.minY + 37.85))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 324.85, frame.minY + 43), controlPoint1: CGPointMake(frame.minX + 337.31, frame.minY + 42.12), controlPoint2: CGPointMake(frame.minX + 331.79, frame.minY + 43.01))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 278.87, frame.minY + 37), controlPoint1: CGPointMake(frame.minX + 311.07, frame.minY + 42.96), controlPoint2: CGPointMake(frame.minX + 292.62, frame.minY + 40.02))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 267.88, frame.minY + 33), controlPoint1: CGPointMake(frame.minX + 275.31, frame.minY + 36.22), controlPoint2: CGPointMake(frame.minX + 271.48, frame.minY + 33.97))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 251.71, frame.minY + 31.69), controlPoint1: CGPointMake(frame.minX + 262.56, frame.minY + 31.57), controlPoint2: CGPointMake(frame.minX + 257.41, frame.minY + 31.53))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 240.89, frame.minY + 34), controlPoint1: CGPointMake(frame.minX + 248.1, frame.minY + 31.78), controlPoint2: CGPointMake(frame.minX + 244.49, frame.minY + 33.89))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 227.13, frame.minY + 33.35), controlPoint1: CGPointMake(frame.minX + 236.55, frame.minY + 34.13), controlPoint2: CGPointMake(frame.minX + 231.82, frame.minY + 33.1))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 214.91, frame.minY + 36), controlPoint1: CGPointMake(frame.minX + 222.93, frame.minY + 33.57), controlPoint2: CGPointMake(frame.minX + 218.75, frame.minY + 35.02))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 191.92, frame.minY + 42), controlPoint1: CGPointMake(frame.minX + 206.3, frame.minY + 38.2), controlPoint2: CGPointMake(frame.minX + 200.19, frame.minY + 41.81))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 165.93, frame.minY + 37), controlPoint1: CGPointMake(frame.minX + 183.49, frame.minY + 42.19), controlPoint2: CGPointMake(frame.minX + 173.88, frame.minY + 36.79))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 154.94, frame.minY + 40), controlPoint1: CGPointMake(frame.minX + 160.51, frame.minY + 37.14), controlPoint2: CGPointMake(frame.minX + 159.34, frame.minY + 38.86))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 136.95, frame.minY + 42), controlPoint1: CGPointMake(frame.minX + 150.15, frame.minY + 41.23), controlPoint2: CGPointMake(frame.minX + 142.16, frame.minY + 41.88))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 105.96, frame.minY + 39), controlPoint1: CGPointMake(frame.minX + 125.29, frame.minY + 42.26), controlPoint2: CGPointMake(frame.minX + 115.12, frame.minY + 38.79))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 82.9, frame.minY + 39.68), controlPoint1: CGPointMake(frame.minX + 97.56, frame.minY + 39.19), controlPoint2: CGPointMake(frame.minX + 89.54, frame.minY + 39.97))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 71.52, frame.minY + 37.63), controlPoint1: CGPointMake(frame.minX + 78.33, frame.minY + 39.48), controlPoint2: CGPointMake(frame.minX + 74.42, frame.minY + 38.03))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 65.98, frame.minY + 38), controlPoint1: CGPointMake(frame.minX + 68.23, frame.minY + 37.19), controlPoint2: CGPointMake(frame.minX + 66.22, frame.minY + 37.82))
        imageRectanglePath.addCurveToPoint(CGPointMake(frame.minX + 61.85, frame.minY + 42.71), controlPoint1: CGPointMake(frame.minX + 65.55, frame.minY + 38.32), controlPoint2: CGPointMake(frame.minX + 63.92, frame.minY + 39.67))
        imageRectanglePath.closePath()
        CGContextSaveGState(context)
        CGContextSetShadowWithColor(context, shadow.shadowOffset, shadow.shadowBlurRadius, (shadow.shadowColor as! UIColor).CGColor)
        CGContextBeginTransparencyLayer(context, nil)
        CGContextSaveGState(context)
        imageRectanglePath.addClip()
        pickedImage.drawInRect(CGRectMake(floor(imageRectangleRect.minX + 0.5), floor(imageRectangleRect.minY + 0.5), pickedImage.size.width, pickedImage.size.height))
        CGContextRestoreGState(context)
        CGContextEndTransparencyLayer(context)
        CGContextRestoreGState(context)
    }

    //// Generated Images

    public class func imageOfSH3(frame frame: CGRect = CGRectMake(0, 0, 474, 372), pickedImage: UIImage = UIImage(named: "pickedImage.png")!) -> UIImage {
        UIGraphicsBeginImageContextWithOptions(frame.size, false, 0)
            SH3_PhotoFrame.drawSH3(frame: CGRectMake(0, 0, frame.size.width, frame.size.height), pickedImage: pickedImage)

        let imageOfSH3 = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return imageOfSH3
    }

}
